import Head from 'next/head';
import Main from "../components/Main/Main";
import MainMobile from "../components/Main/MainMobile";
import React from "react";
import useViewport from "../customHook/useDeviceDetect";
import NotMobile from "../customHook/notMobile";
export default function Home() {
    // let isMobile = useViewport();
    // let notMobile = NotMobile();
    const isMobile = useViewport();
    const notMobile = NotMobile();
    return (
        <React.Fragment>
            <Head>
                <title>ANARDONY</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            {/*<Main/>*/}
            {/*{isMobile ? <React.Fragment><MainMobile/></React.Fragment> : <React.Fragment><Main/></React.Fragment>}*/}
            {/*{(isMobile && !notMobile) ? <MainMobile/> : <Main/> }*/}
            {/*{isMobile ? <MainMobile/> : <Main/>}*/}
            {/*{notMobile ? <Main/> : <MainMobile/>}*/}
        </React.Fragment>
    )
}