import Head from 'next/head';
import Main from "../components/Main";
import browser from 'browser-detect';
export default function Home() {
    const Browser = browser().name;
  return (
    <div>
      <Head>
        <title>anardony</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        {(Browser=="safari") ? <div style={{letterSpacing: '-20px'}}><Main/></div> :  <div style={{letterSpacing: '0px'}}><Main/></div> }
    </div>
  )
}
