import Head from 'next/head';
import Main from "../components/Main";
import {isMobile} from 'react-device-detect';
import store from '../redux/store/store';
import { Provider } from "react-redux";
import MainMobile from "../components/MainMobile";
import React from "react";
export default function Home() {
  return (
    <React.Fragment>
      <Head>
        <title>anardony</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Provider store={store}>
            {isMobile ? <MainMobile/> : <Main/>}
        </Provider>
    </React.Fragment>
  )
}